# Generated by Django 5.2.16 on 2026-07-08 16:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be an Iranian mobile number in E.164 format. Example: +989121234567', regex='^\\+989\\d{9}$')])),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('verify_phone', 'Verify phone'), ('change_phone', 'Change phone'), ('password_reset', 'Password reset')], default='login', max_length=32)),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'created_at'], name='otp_phone_purpose_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('phone_number', ''), _negated=True), name='otp_phone_not_blank'), models.CheckConstraint(condition=models.Q(('code_hash', ''), _negated=True), name='otp_code_hash_not_blank'), models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='otp_max_attempts_positive'), models.CheckConstraint(condition=models.Q(('attempts_count__lte', models.F('max_attempts'))), name='otp_attempts_lte_max')],
            },
        ),
    ]
