# Generated by Django 5.2.16 on 2026-07-13 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_otp_challenge_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'email', 'created_at'], name='email_verify_user_email_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='email_verify_email_not_blank'), models.CheckConstraint(condition=models.Q(('code_hash', ''), _negated=True), name='email_verify_code_hash_not_blank'), models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='email_verify_max_attempts_positive'), models.CheckConstraint(condition=models.Q(('attempts_count__lte', models.F('max_attempts'))), name='email_verify_attempts_lte_max')],
            },
        ),
    ]
