# Generated by Django 5.2.16 on 2026-08-26 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='boards.card')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collaboration.checklist')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_card_comments', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.card')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='boards.board')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CardLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_links', to='boards.card')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_links', to='collaboration.label')),
            ],
        ),
        migrations.CreateModel(
            name='CardAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_card_members', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='boards.card')),
                ('workspace_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to='workspaces.workspacemembership')),
            ],
            options={
                'ordering': ('assigned_at',),
                'constraints': [models.UniqueConstraint(fields=('card', 'workspace_membership'), name='card_assignee_unique_member')],
            },
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='checklist_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.UniqueConstraint(fields=('card', 'position'), name='checklist_unique_card_position'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='checklist_item_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('checklist', 'position'), name='checklist_item_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='comment_body_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='label_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.CheckConstraint(condition=models.Q(('color', ''), _negated=True), name='label_color_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='cardlabel',
            constraint=models.UniqueConstraint(fields=('card', 'label'), name='card_label_unique_pair'),
        ),
    ]
