# Generated by Django 5.2.16 on 2026-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_boardlist_board_list_unique_position_and_more'),
        ('collaboration', '0002_checklist_deleted_at_checklistitem_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='checklist',
            name='checklist_unique_card_position',
        ),
        migrations.RemoveConstraint(
            model_name='checklistitem',
            name='checklist_item_unique_position',
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('card', 'position'), name='checklist_unique_card_position'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('checklist', 'position'), name='checklist_item_unique_position'),
        ),
    ]
