# Generated by Django 5.2.16 on 2026-09-01 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_deleted_at_boardlist_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='boardlist',
            name='board_list_unique_position',
        ),
        migrations.RemoveConstraint(
            model_name='card',
            name='card_unique_list_position',
        ),
        migrations.AddConstraint(
            model_name='boardlist',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('board', 'position'), name='board_list_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('board_list', 'position'), name='card_unique_list_position'),
        ),
    ]
