"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apps.accounts.apps.AccountsConfig",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL"),
}

CACHES = {
    "default": env.cache(
        "CACHE_URL",
        default="locmemcache://navaboard",
    ),
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "otp_request_ip": env("OTP_REQUEST_IP_RATE", default="20/hour"),
        "otp_request_phone": env("OTP_REQUEST_PHONE_RATE", default="3/minute"),
        "otp_verify_ip": env("OTP_VERIFY_IP_RATE", default="60/hour"),
        "otp_verify_phone": env("OTP_VERIFY_PHONE_RATE", default="10/minute"),
        "email_code_request_ip": env(
            "EMAIL_CODE_REQUEST_IP_RATE",
            default="30/hour",
        ),
        "email_code_request_email": env(
            "EMAIL_CODE_REQUEST_EMAIL_RATE",
            default="3/minute",
        ),
        "email_code_verify_ip": env(
            "EMAIL_CODE_VERIFY_IP_RATE",
            default="60/hour",
        ),
        "email_code_verify_email": env(
            "EMAIL_CODE_VERIFY_EMAIL_RATE",
            default="10/minute",
        ),
        "email_login_ip": env("EMAIL_LOGIN_IP_RATE", default="30/minute"),
        "email_login_email": env(
            "EMAIL_LOGIN_EMAIL_RATE",
            default="5/minute",
        ),
        "token_refresh_ip": env("TOKEN_REFRESH_IP_RATE", default="120/hour"),
        "password_mutation_user": env(
            "PASSWORD_MUTATION_USER_RATE",
            default="10/hour",
        ),
    },
    "NUM_PROXIES": env.int("DRF_NUM_PROXIES", default=0),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "CHECK_REVOKE_TOKEN": True,
}

AUTH_REFRESH_COOKIE_NAME = env("AUTH_REFRESH_COOKIE_NAME", default="navaboard_refresh")
AUTH_REFRESH_COOKIE_PATH = env("AUTH_REFRESH_COOKIE_PATH", default="/api/auth/")
AUTH_REFRESH_COOKIE_SAMESITE = env("AUTH_REFRESH_COOKIE_SAMESITE", default="Lax")
AUTH_REFRESH_COOKIE_SECURE = env.bool("AUTH_REFRESH_COOKIE_SECURE", default=not DEBUG)
AUTH_REFRESH_COOKIE_HTTPONLY = True
AUTH_REFRESH_COOKIE_MAX_AGE = int(SIMPLE_JWT["REFRESH_TOKEN_LIFETIME"].total_seconds())

SPECTACULAR_SETTINGS = {
    "TITLE": "NavaBoard API",
    "DESCRIPTION": "API documentation for the NavaBoard project.",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

OTP_DEVELOPMENT_CODE_IN_RESPONSE = env.bool(
    "OTP_DEVELOPMENT_CODE_IN_RESPONSE",
    default=DEBUG,
)


EMAIL_VERIFICATION_DEVELOPMENT_CODE_IN_RESPONSE = env.bool(
    "EMAIL_VERIFICATION_DEVELOPMENT_CODE_IN_RESPONSE",
    default=DEBUG,
)

SMS_PROVIDER = env(
    "SMS_PROVIDER",
    default="console",
)

SMSIR_API_URL = env(
    "SMSIR_API_URL",
    default="https://api.sms.ir/v1/send/verify",
)

SMSIR_API_KEY = env(
    "SMSIR_API_KEY",
    default="",
)

SMSIR_VERIFY_TEMPLATE_ID = env.int(
    "SMSIR_VERIFY_TEMPLATE_ID",
    default=0,
)

SMSIR_CODE_PARAMETER_NAME = env(
    "SMSIR_CODE_PARAMETER_NAME",
    default="CODE",
)

SMSIR_TIMEOUT_SECONDS = env.int(
    "SMSIR_TIMEOUT_SECONDS",
    default=10,
)

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = env(
    "EMAIL_HOST",
    default="",
)

EMAIL_PORT = env.int(
    "EMAIL_PORT",
    default=587,
)

EMAIL_USE_TLS = env.bool(
    "EMAIL_USE_TLS",
    default=True,
)

EMAIL_HOST_USER = env(
    "EMAIL_HOST_USER",
    default="",
)

EMAIL_HOST_PASSWORD = env(
    "EMAIL_HOST_PASSWORD",
    default="",
)

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="NavaBoard <no-reply@navaboard.local>",
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
